###
POST localhost:3000/maestro/sessions/test-session/tracks
Content-Type: application/json

{
  "url": "https://cdn.freesound.org/previews/763/763587_10152894-lq.mp3",
  "name": "my-track2"
}
> {%
  client.global.set("last_created_track_id", response.body.id);
%}

###
### create from directory
POST localhost:3000/maestro/sessions/test-session/tracks/from-directory
Accept: application/json
Content-Type: application/json

{
  "directoryUrl": "https://fourgate.cloud/public/musics"
}

###
### Get one
GET localhost:3000/tracks/{{last_created_track_id}}

###
###
### Get all
GET localhost:3000/maestro/sessions/test-session/tracks

###

### Set created track to current playing
PUT localhost:3000//maestro/sessions/test-session/playing-tracks
Content-Type: application/json

{
  "trackId": "{{last_created_track_id}}",
  "paused": false
}

###

### get playing track
GET localhost:3000/sessions/test-session/playing-tracks

###