###
POST localhost:3000/maestro/sessions/default-current-session/tracks/from-youtube
Content-Type: application/json

{
  "urls": [
    "https://www.youtube.com/watch?v=nkvhwh7CQqA&ab_channel=ForsakenTunes"
  ]
}

###
GET localhost:3000/maestro/sessions/default-current-session/tracks/from-youtube
Content-Type: application/json

