###
POST https://fourgate.cloud/rpg-maestro/admin/tracks
Content-Type: application/json

{
  "url": "https://fourgate.cloud/public/musics/relaxing-celtic-music-forest-sanctum.mp3"
}
> {%
  client.global.set("last_created_track_id", response.body.id);
%}

###10.243.230.63

### Get one
GET https://fourgate.cloud/rpg-maestro/tracks/{{last_created_track_id}}

###

### Set created track to current playing
PUT https://fourgate.cloud/rpg-maestro/admin/sessions/current/tracks
Content-Type: application/json

{
  "trackId": "{{last_created_track_id}}",
  "paused": false
}
###

### get playing track
GET https://fourgate.cloud/rpg-maestro/sessions/current/tracks
###