###
POST localhost:3000/admin/tracks
Content-Type: application/json

{
  "url": "https://cdn.freesound.org/previews/763/763587_10152894-lq.mp3",
  "name": "my-track"
}
> {%
  client.global.set("last_created_track_id", response.body.id);
%}

###
### create from directory
POST localhost:3000/admin/tracks/directory
Accept: application/json
Content-Type: application/json

{
  "directoryUrl": "https://fourgate.cloud/public/musics"
}
###
### Get one
GET localhost:3000/tracks/{{last_created_track_id}}

###
###
### Get all
GET localhost:3000/admin/tracks
###

### Set created track to current playing
PUT localhost:3000/admin/sessions/current/tracks
Content-Type: application/json

{
  "trackId": "{{last_created_track_id}}",
  "paused": false
}
###

### get playing track
GET localhost:3000/sessions/current/tracks
###