name: Release Workflow
on:
  push:
    branches:
      - main

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NX_NO_CLOUD: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: sudo apt-get install ffmpeg -y

      - run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint test deploy --no-cloud --parallel=false
