name: Release Workflow
on:
  push:
    branches:
      - main

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: sudo apt-get install ffmpeg -y

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint test deploy --no-cloud
