name: Build and tests
on:
  pull_request:

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_NO_CLOUD: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
#      - uses: FedericoCarboni/setup-ffmpeg@v3
#        id: setup-ffmpeg
#        with:
#          ffmpeg-version: release
      - run: sudo apt-get install ffmpeg -y

      - run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint build test --no-cloud
      - run: npx nx affected -t e2e --no-cloud
      - run: ls -l dist
        if: ${{ !cancelled() }}

      - name: Upload Playwright Report as Github artifact
        # 'With this report, you can analyze locally the results of the tests. see https://playwright.dev/docs/ci-intro#html-report'
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
