name: Build and tests
on:
  pull_request:

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_NO_CLOUD: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
#      - uses: FedericoCarboni/setup-ffmpeg@v3
#        id: setup-ffmpeg
#        with:
#          ffmpeg-version: release
      - run: sudo apt-get install ffmpeg -y

      - run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint build test e2e --no-cloud
